// TODO: store in npm package

const propertyCards = [
  {
    id: 1,
    name: 'baltic-avenue',
    value: 1,
    type: 'property',
    mainColor: 'brown',
    colors: [],
  },
  {
    id: 2,
    name: 'mediterranean-avenue',
    value: 1,
    type: 'property',
    mainColor: 'brown',
    colors: [],
  },
  {
    id: 3,
    name: 'boardwalk',
    value: 4,
    type: 'property',
    mainColor: 'dark-blue',
    colors: [],
  },
  {
    id: 4,
    name: 'park-place',
    value: 4,
    type: 'property',
    mainColor: 'dark-blue',
    colors: [],
  },
  {
    id: 5,
    name: 'north-carolina-avenue',
    value: 4,
    type: 'property',
    mainColor: 'green',
    colors: [],
  },
  {
    id: 6,
    name: 'pacific-avenue',
    value: 4,
    type: 'property',
    mainColor: 'green',
    colors: [],
  },
  {
    id: 7,
    name: 'pennsylvania-avenue',
    value: 4,
    type: 'property',
    mainColor: 'green',
    colors: [],
  },
  {
    id: 8,
    name: 'connecticut-avenue',
    value: 1,
    type: 'property',
    mainColor: 'light-blue',
    colors: [],
  },
  {
    id: 9,
    name: 'oriental-avenue',
    value: 1,
    type: 'property',
    mainColor: 'light-blue',
    colors: [],
  },
  {
    id: 10,
    name: 'vermont-avenue',
    value: 1,
    type: 'property',
    mainColor: 'light-blue',
    colors: [],
  },
  {
    id: 11,
    name: 'new-york-avenue',
    value: 2,
    type: 'property',
    mainColor: 'orange',
    colors: [],
  },
  {
    id: 12,
    name: 'st.james-place',
    value: 2,
    type: 'property',
    mainColor: 'orange',
    colors: [],
  },
  {
    id: 13,
    name: 'tennessee-avenue',
    value: 2,
    type: 'property',
    mainColor: 'orange',
    colors: [],
  },
  {
    id: 14,
    name: 'st.charles-place',
    value: 2,
    type: 'property',
    mainColor: 'purple',
    colors: [],
  },
  {
    id: 15,
    name: 'virginia-avenue',
    value: 2,
    type: 'property',
    mainColor: 'purple',
    colors: [],
  },
  {
    id: 16,
    name: 'states-avenue',
    value: 2,
    type: 'property',
    mainColor: 'purple',
    colors: [],
  },
  {
    id: 17,
    name: 'short-line',
    value: 2,
    type: 'property',
    mainColor: 'railroad',
    colors: [],
  },
  {
    id: 18,
    name: 'b.-&-o.-railroad',
    value: 2,
    type: 'property',
    mainColor: 'railroad',
    colors: [],
  },
  {
    id: 19,
    name: 'reading-railroad',
    value: 2,
    type: 'property',
    mainColor: 'railroad',
    colors: [],
  },
  {
    id: 20,
    name: 'pennsylvania-railroad',
    value: 2,
    type: 'property',
    mainColor: 'railroad',
    colors: [],
  },
  {
    id: 21,
    name: 'kentucky-avenue',
    value: 3,
    type: 'property',
    mainColor: 'red',
    colors: [],
  },
  {
    id: 22,
    name: 'indiana-avenue',
    value: 3,
    type: 'property',
    mainColor: 'red',
    colors: [],
  },
  {
    id: 23,
    name: 'illinois-avenue',
    value: 3,
    type: 'property',
    mainColor: 'red',
    colors: [],
  },
  {
    id: 24,
    name: 'water-works',
    value: 2,
    type: 'property',
    mainColor: 'utility',
    colors: [],
  },
  {
    id: 25,
    name: 'electric-company',
    value: 2,
    type: 'property',
    mainColor: 'utility',
    colors: [],
  },
  {
    id: 26,
    name: 'ventnor-avenue',
    value: 3,
    type: 'property',
    mainColor: 'yellow',
    colors: [],
  },
  {
    id: 27,
    name: 'marvin-gardens',
    value: 3,
    type: 'property',
    mainColor: 'yellow',
    colors: [],
  },
  {
    id: 28,
    name: 'atlantic-avenue',
    value: 3,
    type: 'property',
    mainColor: 'yellow',
    colors: [],
  },
];

const actionCards = [
  {
    id: 29,
    name: 'deal-breaker',
    value: 5,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 30,
    name: 'deal-breaker',
    value: 5,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 31,
    name: 'debt-collector',
    value: 3,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 32,
    name: 'debt-collector',
    value: 3,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 33,
    name: 'debt-collector',
    value: 3,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 34,
    name: 'double-the-rent',
    value: 0,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 35,
    name: 'double-the-rent',
    value: 0,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 36,
    name: 'forced-deal',
    value: 3,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 37,
    name: 'forced-deal',
    value: 3,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 38,
    name: 'forced-deal',
    value: 3,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 39,
    name: 'forced-deal',
    value: 3,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 40,
    name: 'hotel',
    value: 4,
    type: 'building',
    mainColor: '',
    colors: [],
  },
  {
    id: 41,
    name: 'hotel',
    value: 4,
    type: 'building',
    mainColor: '',
    colors: [],
  },
  {
    id: 42,
    name: 'hotel',
    value: 4,
    type: 'building',
    mainColor: '',
    colors: [],
  },
  {
    id: 43,
    name: 'house',
    value: 3,
    type: 'building',
    mainColor: '',
    colors: [],
  },
  {
    id: 44,
    name: 'house',
    value: 3,
    type: 'building',
    mainColor: '',
    colors: [],
  },
  {
    id: 45,
    name: 'house',
    value: 3,
    type: 'building',
    mainColor: '',
    colors: [],
  },
  {
    id: 46,
    name: 'its-my-birthday',
    value: 2,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 47,
    name: 'its-my-birthday',
    value: 2,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 48,
    name: 'its-my-birthday',
    value: 2,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 49,
    name: 'just-say-no',
    value: 4,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 50,
    name: 'just-say-no',
    value: 4,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 51,
    name: 'just-say-no',
    value: 4,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 52,
    name: 'pass-go',
    value: 1,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 53,
    name: 'pass-go',
    value: 1,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 54,
    name: 'pass-go',
    value: 1,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 55,
    name: 'pass-go',
    value: 1,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 56,
    name: 'pass-go',
    value: 1,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 57,
    name: 'pass-go',
    value: 1,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 58,
    name: 'pass-go',
    value: 1,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 59,
    name: 'pass-go',
    value: 1,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 60,
    name: 'pass-go',
    value: 1,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 61,
    name: 'pass-go',
    value: 1,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 62,
    name: 'sly-deal',
    value: 3,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 63,
    name: 'sly-deal',
    value: 3,
    type: 'action',
    mainColor: '',
    colors: [],
  },
  {
    id: 64,
    name: 'sly-deal',
    value: 3,
    type: 'action',
    mainColor: '',
    colors: [],
  },
];

const propertyWildcards = [
  {
    id: 65,
    name: 'wild-bg',
    value: 4,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['dark-blue', 'green'],
  },
  {
    id: 66,
    name: 'wild-lbbr',
    value: 1,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['light-blue', 'brown'],
  },
  {
    id: 67,
    name: 'wild-op',
    value: 2,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['orange', 'purple'],
  },
  {
    id: 68,
    name: 'wild-op',
    value: 2,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['orange', 'purple'],
  },
  {
    id: 69,
    name: 'wild-gt',
    value: 4,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['green', 'railroad'],
  },
  {
    id: 70,
    name: 'wild-lbt',
    value: 4,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['light-blue', 'railroad'],
  },
  {
    id: 71,
    name: 'wild-ut',
    value: 2,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['utility', 'railroad'],
  },
  {
    id: 72,
    name: 'wild-ry',
    value: 3,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['yellow', 'red'],
  },
  {
    id: 73,
    name: 'wild-ry',
    value: 3,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['yellow', 'red'],
  },
  {
    id: 74,
    name: 'property-wildcard',
    value: 0,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['red', 'green', 'dark-blue', 'light-blue', 'utility', 'yellow', 'orange', 'brown', 'purple', 'railroad'],
  },
  {
    id: 75,
    name: 'property-wildcard',
    value: 0,
    type: 'property_wildcard',
    mainColor: '',
    colors: ['red', 'green', 'dark-blue', 'light-blue', 'utility', 'yellow', 'orange', 'brown', 'purple', 'railroad'],
  },
];

const rentCards = [
  {
    id: 76,
    name: 'rent-bg',
    value: 1,
    type: 'rent',
    mainColor: '',
    colors: ['green', 'dark-blue'],
  },
  {
    id: 77,
    name: 'rent-bg',
    value: 1,
    type: 'rent',
    mainColor: '',
    colors: ['green', 'dark-blue'],
  },
  {
    id: 78,
    name: 'rent-lbbr',
    value: 1,
    type: 'rent',
    mainColor: '',
    colors: ['brown', 'light-blue'],
  },
  {
    id: 79,
    name: 'rent-lbbr',
    value: 1,
    type: 'rent',
    mainColor: '',
    colors: ['brown', 'light-blue'],
  },
  {
    id: 80,
    name: 'rent-op',
    value: 1,
    type: 'rent',
    mainColor: '',
    colors: ['purple', 'orange'],
  },
  {
    id: 81,
    name: 'rent-op',
    value: 1,
    type: 'rent',
    mainColor: '',
    colors: ['purple', 'orange'],
  },
  {
    id: 82,
    name: 'rent-ut',
    value: 1,
    type: 'rent',
    mainColor: '',
    colors: ['railroad', 'utility'],
  },
  {
    id: 83,
    name: 'rent-ut',
    value: 1,
    type: 'rent',
    mainColor: '',
    colors: ['railroad', 'utility'],
  },
  {
    id: 84,
    name: 'rent-ry',
    value: 1,
    type: 'rent',
    mainColor: '',
    colors: ['red', 'yellow'],
  },
  {
    id: 85,
    name: 'rent-ry',
    value: 1,
    type: 'rent',
    mainColor: '',
    colors: ['red', 'yellow'],
  },
];

const rentWildCards = [
  {
    id: 86,
    name: 'rent-wildcard',
    value: 3,
    type: 'rent_wildcard',
    mainColor: '',
    colors: ['red', 'green', 'dark-blue', 'light-blue', 'utility', 'yellow', 'orange', 'brown', 'purple', 'railroad'],
  },
  {
    id: 87,
    name: 'rent-wildcard',
    value: 3,
    type: 'rent_wildcard',
    mainColor: '',
    colors: ['red', 'green', 'dark-blue', 'light-blue', 'utility', 'yellow', 'orange', 'brown', 'purple', 'railroad'],
  },
  {
    id: 88,
    name: 'rent-wildcard',
    value: 3,
    type: 'rent_wildcard',
    mainColor: '',
    colors: ['red', 'green', 'dark-blue', 'light-blue', 'utility', 'yellow', 'orange', 'brown', 'purple', 'railroad'],
  },
];

const moneyCards = [
  {
    id: 89,
    name: '$1',
    value: 1,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 90,
    name: '$1',
    value: 1,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 91,
    name: '$1',
    value: 1,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 92,
    name: '$1',
    value: 1,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 93,
    name: '$1',
    value: 1,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 94,
    name: '$1',
    value: 1,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 95,
    name: '$2',
    value: 2,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 96,
    name: '$2',
    value: 2,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 97,
    name: '$2',
    value: 2,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 98,
    name: '$2',
    value: 2,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 99,
    name: '$2',
    value: 2,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 100,
    name: '$3',
    value: 3,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 101,
    name: '$3',
    value: 3,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 102,
    name: '$3',
    value: 3,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 103,
    name: '$4',
    value: 4,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 104,
    name: '$4',
    value: 4,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 105,
    name: '$4',
    value: 4,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 106,
    name: '$5',
    value: 5,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 107,
    name: '$5',
    value: 5,
    type: 'money',
    mainColor: '',
    colors: [],
  },
  {
    id: 108,
    name: '$10',
    value: 10,
    type: 'money',
    mainColor: '',
    colors: [],
  },
];

export default [...propertyCards, ...propertyWildcards, ...actionCards, ...rentCards, ...rentWildCards, ...moneyCards];
